In [379]:
import pandas as pd
data=pd.read_csv('heart.csv')

In [380]:
data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [381]:
data.shape

(1025, 14)

In [382]:
data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,1.071512,1.385366,0.754146,2.323902,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,1.175053,0.617755,1.030798,0.620660,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [383]:
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [384]:
#dataset is clean and has no missing values

In [385]:
data['target'].value_counts()

1    526
0    499
Name: target, dtype: int64

### dataset is balanced

In [386]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [387]:
#All data are numerical

In [388]:
#let's transform categorical values into dummies/Convert categorical variable into dummy/indicator variables.

data = pd.get_dummies(data, columns = ['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal'])

In [389]:
data

,age,trestbps,chol,thalach,oldpeak,target,sex_0,sex_1,cp_0,cp_1,...,slope_2,ca_0,ca_1,ca_2,ca_3,ca_4,thal_0,thal_1,thal_2,thal_3
0,52,125,212,168,1.0,0,0,1,1,0,...,1,0,0,1,0,0,0,0,0,1
1,53,140,203,155,3.1,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,1
2,70,145,174,125,2.6,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,1
3,61,148,203,161,0.0,0,0,1,1,0,...,1,0,1,0,0,0,0,0,0,1
4,62,138,294,106,1.9,0,1,0,1,0,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,140,221,164,0.0,1,0,1,0,1,...,1,1,0,0,0,0,0,0,1,0
1021,60,125,258,141,2.8,0,0,1,1,0,...,0,0,1,0,0,0,0,0,0,1
1022,47,110,275,118,1.0,0,0,1,1,0,...,0,0,1,0,0,0,0,0,1,0
1023,50,110,254,159,0.0,1,1,0,1,0,...,1,1,0,0,0,0,0,0,1,0
1024,54,120,188,113,1.4,0,0,1,1,0,...,0,0,1,0,0,0,0,0,0,1

In [390]:
#We will test some classification algorithms: Logistic regression, svm, stochastic gradient descent , decision tree, random forest.

In [391]:
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB

The dataset is split into two sets: a training set and a testing set. 70% of the dataset will be used as a training set and 30% will be used for testing.

In [392]:
y = data['target']
X = data.drop('target',axis=1)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [393]:
LR_classifier = LogisticRegression(random_state=0)
clf = svm.SVC()
forest=RandomForestClassifier(n_estimators=20, random_state=12,max_depth=6)
treee = tree.DecisionTreeClassifier(criterion = 'entropy',random_state=0,max_depth = 6)
GBC=GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0)
NB=GaussianNB()

In [394]:
LR_classifier.fit(X_train, y_train)
clf.fit(X_train, y_train)
treee.fit(X_train, y_train)
forest.fit(X_train, y_train)
GBC.fit(X_train, y_train)
NB.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

GaussianNB()

In [395]:
print(forest)

RandomForestClassifier(max_depth=6, n_estimators=20, random_state=12)

In [396]:
print(GBC)

GradientBoostingClassifier(learning_rate=1.0, max_depth=1, random_state=0)

In [397]:
#traing accuracy
y_pred=LR_classifier.predict(X_train)
y_predsvm=clf.predict(X_train)
y_predtree=treee.predict(X_train)
y_predforest=forest.predict(X_train)
y_predGBC=GBC.predict(X_train)
y_predNB=NB.predict(X_train)

In [398]:
print(accuracy_score(y_train, y_pred))
print(accuracy_score(y_train, y_predsvm))
print(accuracy_score(y_train, y_predtree))
print(accuracy_score(y_train, y_predforest))
print(accuracy_score(y_train, y_predGBC))
print(accuracy_score(y_train, y_predNB))

0.8688981868898187
0.691771269177127
0.9497907949790795
0.9525801952580195
0.9595536959553695
0.8368200836820083

In [399]:
#test accuracy
y_pred=LR_classifier.predict(X_test)
y_predsvm=clf.predict(X_test)
y_predtree=treee.predict(X_test)
y_predforest=forest.predict(X_test)
y_predGBC=GBC.predict(X_test)
y_predNB=NB.predict(X_test)

In [400]:
print(accuracy_score(y_test, y_pred))
print(accuracy_score(y_test, y_predsvm))
print(accuracy_score(y_test, y_predtree))
print(accuracy_score(y_test, y_predforest))
print(accuracy_score(y_test, y_predGBC))
print(accuracy_score(y_test, y_predNB))

0.8961038961038961
0.75
0.9188311688311688
0.961038961038961
0.9253246753246753
0.8766233766233766

Printing all accuracies

In [401]:
print("ACCURACY")
print("")
print("Logistic Regression:", accuracy_score(y_test, y_pred)*100,"%")
print("Support Vector Machine:",accuracy_score(y_test, y_predsvm)*100,"%")
print("Decision Tree:",accuracy_score(y_test, y_predtree)*100,"%")
print("Random Forest:",accuracy_score(y_test, y_predforest)*100,"%")
print("Gradient Boosting:",accuracy_score(y_test, y_predGBC)*100,"%")
print("Gaussian Naive Bayes:",accuracy_score(y_test, y_predNB)*100,"%")

ACCURACY

Logistic Regression: 89.6103896103896 %
Support Vector Machine: 75.0 %
Decision Tree: 91.88311688311688 %
Random Forest: 96.1038961038961 %
Gradient Boosting: 92.53246753246754 %
Gaussian Naive Bayes: 87.66233766233766 %

In [402]:
#best model is randomForest

In [403]:
import pickle
pickle.dump(forest, open('Random_forest_model.pkl', 'wb'))